"""
core/qa_state_machine.py — Emthethal AI
=========================================
Gap #2: Formal Human QA State Machine

Defines every lifecycle state a ChecklistTemplate can be in,
the legal transitions between states, and the audit trail.

State diagram:
  INGESTED
    → EXTRACTED       (OCR/parsing complete)
    → GENERATED       (LLM produced canonical schema)
    → QA_PENDING      (awaiting human QA review)
    → APPROVED        (QA manager approved)
    → LIVE            (active, submissions accepted)
    → CLOSED          (archived, no new submissions)

From QA_PENDING:
    → REJECTED        (QA manager rejected — goes back to GENERATED for rework)
    → QUARANTINED     (below confidence threshold — needs human review)

From APPROVED:
    → SUPERSEDED      (a new version has been approved, this is now historical)

Rule: FastAPI owns all state transitions.
"""

import logging
from datetime import datetime
from enum import Enum
from typing import Optional

logger = logging.getLogger(__name__)


# ── States ─────────────────────────────────────────────────────────────────────

class FormLifecycleState(str, Enum):
    """All possible lifecycle states for a ChecklistTemplate."""
    INGESTED    = "INGESTED"       # Source document received
    EXTRACTED   = "EXTRACTED"      # OCR + geometry extraction complete
    GENERATED   = "GENERATED"      # Canonical schema + Form.io generated by LLM
    QUARANTINED = "QUARANTINED"    # Below confidence threshold, needs human triage
    QA_PENDING  = "QA_PENDING"     # Awaiting human QA review
    REJECTED    = "REJECTED"       # QA rejected — can be re-generated
    APPROVED    = "APPROVED"       # QA approved, ready to push
    LIVE        = "LIVE"           # Active, accepting field submissions
    SUPERSEDED  = "SUPERSEDED"     # Replaced by a newer version (historical)
    CLOSED      = "CLOSED"         # Archived, no new submissions


# ── Legal Transitions ──────────────────────────────────────────────────────────

# Maps each state to the set of states it may legally transition TO.
# Any transition not listed here is illegal and will raise StateTransitionError.
_LEGAL_TRANSITIONS: dict[FormLifecycleState, set[FormLifecycleState]] = {
    FormLifecycleState.INGESTED:    {FormLifecycleState.EXTRACTED},
    FormLifecycleState.EXTRACTED:   {FormLifecycleState.GENERATED, FormLifecycleState.QUARANTINED},
    FormLifecycleState.GENERATED:   {FormLifecycleState.QA_PENDING, FormLifecycleState.QUARANTINED},
    FormLifecycleState.QUARANTINED: {FormLifecycleState.QA_PENDING, FormLifecycleState.CLOSED},
    FormLifecycleState.QA_PENDING:  {FormLifecycleState.APPROVED, FormLifecycleState.REJECTED, FormLifecycleState.QUARANTINED},
    FormLifecycleState.REJECTED:    {FormLifecycleState.GENERATED},   # re-generate after fix
    FormLifecycleState.APPROVED:    {FormLifecycleState.LIVE, FormLifecycleState.SUPERSEDED, FormLifecycleState.CLOSED},
    FormLifecycleState.LIVE:        {FormLifecycleState.SUPERSEDED, FormLifecycleState.CLOSED},
    FormLifecycleState.SUPERSEDED:  {FormLifecycleState.CLOSED},
    FormLifecycleState.CLOSED:      set(),   # terminal
}

# States that require a human actor (audit fields mandatory)
_HUMAN_ACTOR_REQUIRED: set[FormLifecycleState] = {
    FormLifecycleState.APPROVED,
    FormLifecycleState.REJECTED,
    FormLifecycleState.CLOSED,
    FormLifecycleState.QUARANTINED,  # when triggered manually
}


# ── Exceptions ─────────────────────────────────────────────────────────────────

class StateTransitionError(Exception):
    """Raised when an illegal state transition is attempted."""

    def __init__(
        self,
        from_state: FormLifecycleState,
        to_state: FormLifecycleState,
        template_id: Optional[int] = None,
    ):
        self.from_state = from_state
        self.to_state = to_state
        msg = (
            f"Illegal state transition: {from_state.value} → {to_state.value}"
            + (f" (template_id={template_id})" if template_id else "")
        )
        super().__init__(msg)


# ── Transition Record (audit log entry) ───────────────────────────────────────

class StateTransitionRecord:
    """
    Immutable record of a single state transition.
    Write one of these to QAStateAuditLog for every state change.
    """

    def __init__(
        self,
        template_id: int,
        from_state: FormLifecycleState,
        to_state: FormLifecycleState,
        actor: str,  # "system" | "user:<id>"
        notes: Optional[str] = None,
    ):
        self.template_id = template_id
        self.from_state = from_state
        self.to_state = to_state
        self.actor = actor
        self.notes = notes
        self.transitioned_at = datetime.utcnow()

    def to_dict(self) -> dict:
        return {
            "template_id":     self.template_id,
            "from_state":      self.from_state.value,
            "to_state":        self.to_state.value,
            "actor":           self.actor,
            "notes":           self.notes,
            "transitioned_at": self.transitioned_at.isoformat(),
        }


# ── State Machine ──────────────────────────────────────────────────────────────

class FormStateMachine:
    """
    Stateless validator. The actual state is stored in the DB.
    Call validate_transition() before writing to DB.
    """

    @staticmethod
    def validate_transition(
        from_state: FormLifecycleState,
        to_state: FormLifecycleState,
        actor: str,
        template_id: Optional[int] = None,
    ) -> StateTransitionRecord:
        """
        Validates that from_state → to_state is legal.
        Returns a StateTransitionRecord ready to be persisted.
        Raises StateTransitionError if illegal.
        """
        legal = _LEGAL_TRANSITIONS.get(from_state, set())
        if to_state not in legal:
            raise StateTransitionError(from_state, to_state, template_id)

        if to_state in _HUMAN_ACTOR_REQUIRED and actor == "system":
            logger.warning(
                f"State transition to {to_state.value} should have a human actor, "
                f"got 'system'. (template_id={template_id})"
            )

        record = StateTransitionRecord(
            template_id=template_id or -1,
            from_state=from_state,
            to_state=to_state,
            actor=actor,
        )
        logger.info(
            f"State transition: {from_state.value} → {to_state.value} "
            f"[actor={actor}, template_id={template_id}]"
        )
        return record

    @staticmethod
    def is_terminal(state: FormLifecycleState) -> bool:
        return not _LEGAL_TRANSITIONS.get(state)

    @staticmethod
    def can_accept_submissions(state: FormLifecycleState) -> bool:
        return state == FormLifecycleState.LIVE

    @staticmethod
    def next_states(state: FormLifecycleState) -> list[FormLifecycleState]:
        return sorted(_LEGAL_TRANSITIONS.get(state, set()), key=lambda s: s.value)


# Singleton
form_state_machine = FormStateMachine()
